import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DuckPond",
  description: "Generated by DuckPond",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-300 ease-in-out`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              className: '',
              duration: 3000,
              style: {
                background: 'var(--background)',
                color: 'var(--foreground)',
                border: '1px solid var(--border)',
              },
              success: {
                iconTheme: {
                  primary: '#4CAF50',
                  secondary: 'var(--background)',
                },
                style: {
                  background: 'var(--background)',
                  color: 'var(--foreground)',
                  border: '1px solid #4CAF50',
                },
              },
              error: {
                iconTheme: {
                  primary: '#f44336',
                  secondary: 'var(--background)',
                },
                style: {
                  background: 'var(--background)',
                  color: 'var(--foreground)',
                  border: '1px solid #f44336',
                },
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
